packages:
  - packages/*
  - apps/*
  - scripts/*

catalog:
  '@antfu/eslint-config': ^5.0.0
  '@babel/core': ^7.28.0
  '@babel/preset-env': ^7.28.0
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@element-plus/icons-vue': ^2.3.2
  '@koa/bodyparser': ^6.0.0
  '@koa/cors': ^5.0.0
  '@koa/multer': ^4.0.0
  '@koa/router': ^13.1.1
  '@types/fs-extra': ^11.0.4
  '@types/koa': ^3.0.0
  '@types/koa-logger': ^3.1.5
  '@types/koa-static': ^4.0.4
  '@types/koa__cors': ^5.0.0
  '@types/koa__router': ^12.0.4
  '@types/md5': ^2.3.5
  '@types/pug': ^2.0.10
  '@types/ramda': ^0.31.0
  '@types/superagent': ^8.1.9
  '@vue/language-plugin-pug': ^3.0.5
  '@vue/tsconfig': ^0.7.0
  ajv: ^8.17.1
  axios: ^1.11.0
  babel-loader: ^10.0.0
  commander: ^14.0.0
  commitizen: ^4.3.1
  css-loader: ^7.1.2
  cz-git: ^1.12.0
  element-plus: ^2.10.6
  eslint: ^9.32.0
  execa: ^9.6.0
  fs-extra: ^11.3.0
  html-webpack-plugin: ^5.6.3
  koa: ^3.0.1
  koa-logger: ^4.0.0
  koa-static: ^5.0.0
  lint-staged: ^16.1.2
  log4js: ^6.9.1
  md5: ^2.3.0
  multer: ^2.0.2
  picocolors: ^1.1.1
  pinia: ^3.0.3
  pug: ^3.0.3
  pug-plain-loader: ^1.1.0
  ramda: ^0.31.3
  raw-loader: ^4.0.2
  sass: ^1.90.0
  sass-loader: ^16.0.5
  simple-git-hooks: ^2.13.0
  style-loader: ^4.0.0
  superagent: ^10.2.3
  thread-loader: ^4.0.4
  tiny-glob: ^0.2.9
  ts-loader: ^9.5.2
  tsx: ^4.20.3
  typescript: ^5.9.2
  unbuild: ^3.6.1
  unplugin-auto-import: ^20.0.0
  unplugin-icons: ^22.2.0
  unplugin-vue-components: ^29.0.0
  vitest: ^3.2.4
  vue: ^3.5.18
  vue-loader: ^17.4.2
  vue-router: ^4.5.1
  vue-style-loader: ^4.1.3
  webpack: ^5.101.0
  webpack-dev-middleware: ^7.4.2
  webpack-dev-server: ^5.2.2
  webpack-hot-middleware: ^2.26.1
  webpack-merge: ^6.0.1

onlyBuiltDependencies:
  - esbuild
